apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: yelb-ui

---

apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4567
      targetPort: 4567
  selector:
    app: yelb-appserver

---

apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-server

---

apiVersion: v1
kind: Service
metadata:
  name: yelb-db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: yelb-db
